### ISSUE TITLE
Trying to compile my own flavour of miniVector

### ISSUE THREAD

**Issue by bahur142** [LiMium/mini-vector-android#36]
Hello
I know this is not the right place for that, but I am looking for a help to compile my own flavour. I am now to the point that successfully compiled the APK from this repo with Android Studio 4.0.
Unfortunately the app crashes on start. The steps I am following are from the Readme file:

- I have created firebase account and created my own app.
- I managed to edit the **build.gradle** file and add section **myriot**.
- Then copied the folder **app** and renamed it to **myriot**
- Then downloaded **google-services.json** from my firebase console and put it in vector/src/myriot/
- I copied vector/src/main/AndroidManifest.xml to vector/src/myriot/AndroidManifest.xml and edited
 **android:label="Riot Cloud01"**
The app compiles and successfully installs on the phone, but crashes when start. It says:

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/R$string;
at com.google.android.gms.common.internal.StringResourceValueReader.<init>(Unknown Source:4)
at com.google.firebase.FirebaseOptions.fromResource(com.google.firebase:firebase-common@@19.0.0:156)
at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.0.0:240)
at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@19.0.0:51)
at android.content.ContentProvider.attachInfo(Unknown Source:70)
at android.content.ContentProvider.attachInfo(Unknown Source:1)
at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.0.0:45)
at android.app.ActivityThread.installProvider(Unknown Source:247)
at android.app.ActivityThread.installContentProviders(Unknown Source:28)
at android.app.ActivityThread.handleBindApplication(Unknown Source:1183)
at android.app.ActivityThread.access$1200(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(Unknown Source:720)
at android.os.Handler.dispatchMessage(Unknown Source:21)
at android.os.Looper.loop(Unknown Source:210)
at android.app.ActivityThread.main(Unknown Source:107)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
at com.android.internal.os.ZygoteInit.main(Unknown Source:281)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.R$string" on path: DexPathList[[zip file "/data/app/org.cloud01.myriot-IY5e83B4l2-fD-gbyJMJnw==/base.apk"],nativeLibraryDirectories=[/data/app/org.cloud01.myriot-IY5e83B4l2-fD-gbyJMJnw==/lib/arm, /data/app/org.cloud01.myriot-IY5e83B4l2-fD-gbyJMJnw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 18 more

`

Obviously I am missing something, but I am not a developer and don't know what is it.
Would you help me to figure out where is the problem?

**Comment by hrj** [comment]
> but I am not a developer

Firstly, congrats for making it this far! I can't help you in detail, but I can give you some pointers to chase.

Are you able to compile the unmodified code, without modifications and run it? If not, then that is a good starting point.

It looks like the compiled apk doesn't contain the cloud messaging library for push notifications, and yet is trying to find it. The f-droid flavour doesn't contain this library. So probably there is some cross-connection happening between the various flavours.

Lastly, this code base is not very pristine and well maintained. When I started making this fork, I was not aware of gradle's "flavour" functionality, so I might have jinxed the build files. You might have better luck working with the upstream code (which BTW, they are soon going to deprecate and move to a new codebase called RiotX).

Summary: Good luck; you will need it :)
